# Generated by Django 3.0.4 on 2020-03-30 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.SmallIntegerField(default=0)),
                ('dual_positive_count', models.SmallIntegerField(default=0)),
                ('ccu_pos_covid_neg_count', models.SmallIntegerField(default=0)),
                ('ccu_neg_covid_pos_count', models.SmallIntegerField(default=0)),
                ('dual_negative_count', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.SmallIntegerField(null=True)),
                ('CCU', models.SmallIntegerField(null=True)),
                ('COVID', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_to_distribute', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptimalCensus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.SmallIntegerField(null=True)),
                ('CCU', models.FloatField(null=True)),
                ('COVID', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedCensus',
            fields=[
                ('census_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='distribute_patients.Census')),
            ],
            bases=('distribute_patients.census',),
        ),
        migrations.CreateModel(
            name='FinalCensus',
            fields=[
                ('census_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='distribute_patients.Census')),
            ],
            bases=('distribute_patients.census',),
        ),
        migrations.CreateModel(
            name='StartingCensus',
            fields=[
                ('census_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='distribute_patients.Census')),
            ],
            bases=('distribute_patients.census',),
        ),
        migrations.CreateModel(
            name='PatientAssignmentLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_batting_order', models.SmallIntegerField()),
                ('affinity_for_COVID_pos_CCU_pos_patients', models.FloatField(default=0)),
                ('count_of_dual_positives_needed_to_fill', models.SmallIntegerField(default=0)),
                ('allocated_counts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distribute_patients.AllocatedCounts')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='distribute_patients.Distribution')),
                ('optimal_census', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribute_patients.OptimalCensus')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribute_patients.Provider')),
                ('assigned_census', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribute_patients.AssignedCensus')),
                ('starting_census', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribute_patients.StartingCensus')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_designation', models.SmallIntegerField()),
                ('CCU', models.BooleanField(default=False)),
                ('COVID', models.BooleanField(default=False)),
                ('bounce_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribute_patients.Provider')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribute_patients.Distribution')),
                ('patient_assignment_line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patients', to='distribute_patients.PatientAssignmentLineItem')),
            ],
        ),
    ]
